# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Page settings
title: 沖縄Ruby会議02
email: okinawarb@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  2018/03/10 (Sat) @ 琉球大学 工学部１号館 大教室 322

permalink: /:title
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ruby.okinawa" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: okinawarb
github_username:  okinawarb
show_downloads: false
google_analytics:

# Build settings
theme: jekyll-theme-merlot
markdown: kramdown
plugins:
  - jekyll-feed
source:      ./
destination: ./_site
timezone: Asia/Tokyo
encoding: utf-8

highlighter: rouge
markdown: kramdown
plugins:  ['kramdown']

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - README.md
  - Procfile
  - Gemfile
  - Gemfile.lock
  - config.ru
  - vendor
  - app.json
  - test
  - spec
